### ISSUE TITLE
msvc14 causing 'could not deduce template argument'

### ISSUE THREAD

**Issue by kanekotic** [dascandy/hippomocks#39]
I am working in a project that uses Hippomocks for c++. Currently we are trying to move to VS2015. somehow between msvc12 and msvc14 i start having compilation errors.

I have the next code on the mock:
``` cpp
    auto myMock = make_shared_mock<IMyInterface>(mocks);
    mocks.ExpectCall(myMock.get(), IMyInterface::Method).With(make_shared<MyParameter>()).Return(make_shared<MyResult>());
``` 

And the signature of my Interface is:
``` cpp
struct IMyInterface
{
	virtual ~IMyInterface() = default;
	virtual MyResultPtr Method(const MyParameterPtr& request) const = 0;
        //it has also a variadic template 'Method' and a 'AsyncMethod' definition
};
``` 
I am currently getting the error:

`Error	C2783	'HippoMocks::TCall<Y,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P> &HippoMocks::MockRepository::RegisterExpect_(Z2 *,Y (__stdcall Z::* )(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P) const,HippoMocks::RegistrationType,const char *,const char *,unsigned long)': could not deduce template argument for 'Y'`

am I doing something wrong? Is HippoMocks compatible with msvc14?

**Comment by dascandy** [comment]
Have to admit that I haven't tried it on MSVC2015 yet. Will do that tonight when I have a Windows computer near me.

**Comment by kanekotic** [comment]
thanks for the fast reply, I will try to Isolate the behaviour and also let you know :)

by the way...great job with hippomocks

**Comment by kanekotic** [comment]
I isolated the code and found a way to consistently reproduce it, The next code will always fail:

``` cpp
struct MyResult
{
};

struct MyParameter
{
};

struct IMyInterface
{
	virtual ~IMyInterface() = default;
	virtual MyResult* Method(const MyParameter*& request) const = 0;
	template <typename T, typename ...ARGS> std::shared_ptr<typename T::Response> Method(ARGS&& ...args) const
	{
		return NULL;
	}
};

BOOST_AUTO_TEST_CASE(DispatcherCanWriteSingleRegisterToModbus)
{
	MockRepository mocks;
	auto myMock = make_shared_mock<IMyInterface>(mocks);
	mocks.ExpectCall(myMock.get(), IMyInterface::Method).With(std::make_shared<MyParameter>().get()).Return(std::make_shared<MyResult>().get());
	BOOST_CHECK_NO_THROW(mocks.VerifyAll());
}
```

so my finding is:
* This is happening due the variadic template having the same name as the Method that wants to be mock.
* it works perfectly find with msvc12 but not with msvc14, so something has changed from the msvc compiler.

**Comment by dascandy** [comment]
That's probably a bugfix then, because that variadic template should be considered for the overload set. You can't use ExpectCall flat with an overloaded function, because you'd have to specify which of the overloads it is and you then need to put that cast *before* the ampersand, that HippoMocks adds there for you. So to have the convenient syntax nearly always, but the ability to do overloaded functions, there's an ExpectCallOverload which does not add that ampersand, so you can select a function.

Use it like:
mocks.ExpectCallOverload(myMock.get(), (MyResult* (const MyParameter*&) const)&IMyInterface::Method).With(std::make_shared<MyParameter>().get()).Return(std::make_shared<MyResult>().get())

I did not test that suggestion, but the general idea is to do a manual selection on the function.

Does that help?

**Comment by kanekotic** [comment]
ok worked, thanks a lot... the final signature that made it was 
```cpp
mocks.ExpectCallOverload(myMock.get(), (MyResult*(IMyInterface::*)(const MyParameter*&) const)&IMyInterface::Method).With(std::make_shared<MyParameter>().get()).Return(std::make_shared<MyResult>().get());
```
