### ISSUE TITLE
Mocking a function in a shared library gets ignored

### ISSUE THREAD

**Issue by rianquinn** [dascandy/hippomocks#45]
I am currently using GCC 5.2 on x86-64. I have a simple test app with a shared library that I am compiling using the same compiler, the only difference is the source is .c (so I have some extern "C" code in the test to link properly). 

in the library, I have a simple function:

```
in foo1(void)
{
    return 10;
}

int foo2(int arg)
{
    return arg + foo1();
}
```

and in my test code:

```
MockRepository mocks;
mocks.OnCallFunc(foo1).Return(0);
std::cout << foo2(1) << std::endl;         // returns 11, when it should return 1
```

Now.... thinking about it for a minute, I added this to the test code

```
int foo1(void)
{
    return ::foo1()
}
```

And all of a sudden, the test works fine (i.e. foo2 will return 1). Any ideas? Seems like a bug so I figured I would report it as the documentation doesn't state that you have to override C functions to make this work. 

Other than that, I noticed that trying to overload functions like the POSIX "ioctl" and "open" don't play nice with HippoMocks as they have variadic arguments, but I would love to be able to mock these up as well at some point.

**Comment by dascandy** [comment]
Variadic functions is its own can of worms, and actually poses a giant problem for the way that HippoMocks works. The basis of function mocking is checking the arguments to see if it is a certain call, and if it does not match any to complain. Variadic functions do not report how many arguments they have, so you technically cannot compare them to see if they match a certain expectation, because they might not have written those bytes and then you basically invoke undefined behaviour. You also get false-matches, people calling printf("%u\n", 0x3F800000) and it matching the call for EXPECT_CALL(printf).With(1.0f). Not to mention that you'd have to teach it the rules for parameter expansion, such as that the 1.0f on printf is actually always a double.

In short, it would be good, but I don't think it's going to happen because of those limitations.

With regards to your actual bug report though, that's an interesting corner case. I think, but haven't checked, that you basically get two PLT entries for that function, one in your executable and one in the DLL. You also have the actual function in the DLL. So if you're asking for the address of the function, there's three possible answers for the runtime and they're technically all correct - except that there's three of them, and we can only get one of them. So we get the address of the PLT stub on the executable's side, which we can mock. But the library function will go from the library's PLT stub to the library function, so it is not actually affected.

If however you do override the function, you don't have a PLT entry (that's essentially only for imports), but you do have a function. The PLT entry of the library will point to your function and the library's function is unused. Your mock actually hits the function start now, and it works for the library function.

This is a side-effect of how it's implemented. The only alternative to this is to have actual functions overriding the imported functions in all cases and to make those actual mock functions, possibly with a dllimport / dlsym for the underlying implementation function. That would work, but is much less user-friendly, and more in a GMock-style of working, where you need to explicitly define the mock function.

In a way the behaviour is "correct" though - the library does not export the information that foo2 uses foo1 and foo2 keeps working as it did, so mocking one API function does not inadvertently modify another. Not saying you won't cause bugs this way, but that's at least a way to look at it.

I don't think this is a fixable thing within the scope of HippoMocks' approach.

**Comment by rianquinn** [comment]
Yeah for the project I am actually working on right now, we implemented our own ELF loader, giving me a much better understanding of what's going on (which gave me the idea to do a function override), as it made sense to me that the code in the shared library was getting it's pointer from it's own PLT which HippoMocks doesn't have access to. Sadly, overriding the function doesn't work in all cases, as some seem to cause infinite recursive loops (my suspicion is the global lookup that ld.so might just be returning the first symbol it sees, which means that some will work, and some won't). 

To further prove that the PLT is the issue, I recompiled everything using static library instead, and it works as expected. I would agree that the only way to solve this would be to use something like dlsym. You could however, possibly provide another function for function overriding that takes the library you wish to get the symbol from. For example, you could use dlopen and dlsym to grab the PLT entry for symbol in question, and then do the overload, likely only requiring one additional function argument (almost like the object argument you use for classes). 

As for support for variadic functions, it's easy enough to "constrain" these functions such that they do not need the extra arguments (maybe just providing an example in the docs on why and how to do that). IIRC POSIX makes them variadic for detecting edge cases, and the extra arguments are unused, thus.... in testing we really should "wrap" the call to constrain the number of arguments anyways (i.e. the user of Hippo Mocks should be fixing this problem). Not to mention...... from a TDD point of view, functions like printf (or worse, scanf) are not good things to use outright as they take a seemingly infinite combination of inputs, for which, the past has proven some of those inputs can be disastrous (i.e. the classic buffer overflow).

**Comment by rianquinn** [comment]
Figured I would follow up on this as I have learned a lot more since I last posted this error. 

Trying to hook a function in a shared library seems to depend on the function name itself. Sometimes it works, sometimes it doesn't. I'm 99% sure it has to do with the ELF loader's hashing function, and the order of when a library is loaded. If the loader can find the symbol in the right order, the hook makes it into the shared library, but otherwise it doesn't in which case, the hook appears to be local. 

Our current solution (since we control the shared libraries), is to mark the functions that need to be mocked as weak. Then, in our test code, we provide our own implementation which is always used in place of the weak version. Sadly, this means we are not using OnCallFunc to do this, which I would prefer. Our approach is solid, but a real pain 😄 

I'm not entirely sure how to fix this, other than having to find the address of the symbol in each shared library and hook from there (meaning you have to hook for each loaded shared library, and not just the local executable). I'm not sure if that helps, but this is certainly a feature I would love to see someday. 

At ay rate, love this library. I wish more people used it and took unit testing seriously.

**Comment by dascandy** [comment]
That's odd. In most cases your software will either have the implementation and a PLT entry, or just the PLT entry. If you have both, it will return typically the PLT entry if you look it up, and point the PLT entry to the actual implementation. The mock will then replace your PLT entry (as that's what you get when you look it up) with the mock function, and your calls will be redirected. If the call site resolves directly to the function (or has it inlined), there's no possible way to replace it.

Another library will also have a PLT entry and an actual function. It depends heavily on your compiler what happens exactly - either the function is resolved directly to the actual function, or to the library's PLT, or to the actual target function. In all three of those cases though, it'll not effectively be mocked. If it's inlined it's not replaced either, of course.

This is the downside of the C function mocking. It requires your environment to be controlled and it does not always work despite best efforts.

The upside is that it does at least allow you to do this. It makes error testing on low level functions much easier, and allows you to test things that result in calls to assert, abort or exit (for example).

Marking the functions as weak most likely ensures you will get a PLT entry that points to it. If your own code then does not have a PLT entry it will redirect to the actual function and mock that - and then the library *does* get a mocked function. That may actually be what happens here - can you check that?

**Comment by rianquinn** [comment]
So when we implemented our own ELF loader [here](https://github.com/Bareflank/hypervisor/tree/master/bfelf_loader) one issue we had was with dynamic_cast and exception logic. Working with a Clang developer, we were able to figure out that it was due to the fact that I wasn't handling weak references correctly. There is a one liner in the IA64 spec that states that all weak references must be resolved to the same address across all libraries. This applies to all weak and one global, but in this case, all references must resolve to the global symbol across all libraries. So in this case, making the function weak in the library causes the ELF loader to resolve the libraries symbol to the global symbol in my unit test, which is why it works. 

What I don't know is if marking the symbol weak in the library, and then providing a global symbol in my unittest and then mocking that, provides a means to mock the library as well. That I will test once I get a chance as I am curious to see if that works. 

I will say that none of this is an issue if you statically link everything. The problem with that is static linking is such a pain. 😄 I'll report back once I have more info.

**Comment by dascandy** [comment]
That's an interesting observation. I did not know that about weak symbols. I wonder if that could be (ab)used in HippoMocks to enforce some symbols to not get PLT entries like that, so that the mocking will be more reliable?

**Comment by rianquinn** [comment]
That's what I want to figure out. It might also be possible to get the address of a symbol for each library, and hook each one individually. My understanding is (I could be wrong) is that when you get an address of a symbol from code, you are actually getting a PLT entry, in which case, if you get an address from each library, each one should be different. I'm not sure how that would work on Windows though, but it might be possible on Linux.

**Comment by dascandy** [comment]
When you look up the address of a function in an executable, you get a PLT entry *or* the actual function. When you lookup the address of a function in a shared lib, you also get a PLT entry *or* the actual function. And of course both PLT entries are different, because each gets his own.

**Comment by rianquinn** [comment]
Are you sure you get the actual function if "-fpic" is enabled? Seems to me it would have to be in the PLT.

**Comment by dascandy** [comment]
It's been a while since I tested this - I was mostly surprised that the exact same code linked into two locations could give a different result. -fpic doesn't guarantee use of the PLT; it just guarantees that it's position-independent. For data that does mean GOT use, but for functions you can use RIP-relative jumps to get the same and local jumps should do that for performance reasons.

**Comment by rianquinn** [comment]
I think if a symbol is marked global or weak, it has to be in the PLT. The only thing that it can do that with (at least with ELF) are static (i.e. local) functions. I certainly could be wrong as it has been a while for me too, but I think I remember asking this very question on OSDev, and a couple people came back saying that if it's marked global or weak, it has to be put into the PLT because the compiler / linker doesn't know if the symbol will be used by other compilation units (i.e. other object files). So even though the optimization could occur, it doesn't.

**Comment by dascandy** [comment]
It has to be in the symbol table. Unless I'm very wrong, the linker should be the one making the PLT. No object files have PLTs. It also has to be in dynsym (unless explicitly hidden) as other linkage units may depend on this function to be imported there (RTLD_GLOBAL from the back of my mind, plus an interesting plugin architecture).

In fact, as far as I understand it you could do all global linking with PIC / PIE without PLTs assuming you have full-range IP-relative addressing for jumps. If you have full IP relative locating for data too, you should even be able to omit the GOT. Both are only intended for library / executable replacement so that if you have two mallocs, that the executable will in the end only use one and always use the same one (again, AFAIK).

Do you have a link to the OSDev discussion?

**Comment by rianquinn** [comment]
Sadly I think I asked the question on IRC. But what your saying makes a lot of sense to me, which is why I asked in the first place (because it seemed to me the optimizations your describing should be possible). A whole bunch of people jumped on my like I had spoke ill about god, and they all seemed to agree that GCC doesn't do this type of optimization, but I am certainly not an expect on this and at this point I'm just regurgitating what others said about a year ago. 

But I think this get's to the heart of the problem. When shared libraries get involved, I don't think there is a guaranteed way to hook a function without going to each library and hooking the symbol. It's the only way that I can think of that would work regardless of whether this optimization is enabled or not (other than the fact that I'm not sure how hooking works at all if a relative jump is used). Do you know of any way to lookup each library that was loaded, and do the hook on a per-library basis?

**Comment by dascandy** [comment]
You can do that with dlsym if you have the handles to the libraries - which you don't, and will not be able to get. Alternatively, you could not have any PLT entries at all and just have one address for a function exist, but that means that your full loader will have to relocate everything at that time. Given the speed of computers now, I'm actually not sure if that would be bad. I tried to make a small linker project (zelda - also here on github) to try it out but haven't gotten to that part yet; it only does static linking so far, and I got stuck with not having 32-bit libraries for everything and dropped it for a bit.

Anyway, the root problem is that functions don't have one unique address - because of PLT, inlining, unrolling - so replacing it requires that you at least replace the one that's used. Weak may be able to help there wrt PLT, but not the others.

**Comment by rianquinn** [comment]
Yeah, if inlining is enabled, your screwed, and I think it's reasonable to state that inlining is not supported for testing. Weak certainly works (we are using it [here](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/src/intrinsics/src/vmx_intel_x64_mock.cpp)) with great success, but Hippomocks is not used to make this work. To perform the hook you simply define a global symbol in your unit test and mock from there with the obvious problem being that you have to provide all of the scaffolding to perform an "expect" check, which is where Hippomocks would be nice. The problem with this approach is this only works for libraries you have control of.
