### ISSUE TITLE
No function to undo c-style function hooks

### ISSUE THREAD

**Issue by rianquinn** [dascandy/hippomocks#47]
At the moment, it appears that the only way to undo changes to c-style functions is to destroy the MockRepository. The result is I have to do something like this to get the original functionality of a hooked function back:

```
    do_somthing
    do_somthing

    {
        MockRepository mocks;
        mocks.OnCallFunc(resolve_symbol).Return(-1);

        RUN_UNITTEST_WITH_MOCKS(mocks, [&]
        {
            EXPECT_TRUE(common_dump_vmm() == BF_ERROR_FAILED_TO_DUMP_DR);
        });
    }

    do_somthing
    do_somthing
```

I was thinking of submitting a PR that moves the destructor code to a function called "doDestroy" that the destructor calls, but could also be called manually if desired. Thoughts?

**Comment by dascandy** [comment]
I think I missed the notification for this issue due to Christmas...

The problem with adding this ability is that it does not play nicely with threads. If you have any asynchronous operations in your tests, currently HippoMocks should play nice with that and work well. In case you allow a function to be un-mocked, you run the risk that a piece of code is running through the assembly as it is being overwritten, leading to unpredictable behaviour and crashes. There are ways to avoid this, but they involve much more complicated jumps and knowledge of the assembly code than is currently possible (at least for X86; ARM is easier for this). In short, I would opt for allowing multithreaded tests rather than runtime un-mocking of functions; especially as there already is a workaround.

**Comment by dascandy** [comment]
The idea for a mock is to be a permanent replacement for the duration of your test. You can use the Replace code separately to hook a function for the duration of your Replace object, if you want the function only replaced for a part of the duration.
