### ISSUE TITLE
ARM 64 bit support

### ISSUE THREAD

**Issue by chinux23** [dascandy/hippomocks#57]
From the code, it looks like it only support ARM 32 bit.
Wondering if it's possible to add ARM 64 bit support?

I am very new to the library, the following code is mysterious to me.
Any reference I can lookup to understand what's going on for ARM 32 bit? Maybe I could apply the similar logic to ARM 64 bit.

``` C++
    unsigned int *rawptr = (unsigned int *)((intptr_t)(origFunc) & (~3));
    if ((intptr_t)origFunc & 1) {
      rawptr[0] = 0x6800A001;
      rawptr[1] = 0x46874687;
      rawptr[2] = (intptr_t)replacement;
    } else {
      rawptr[0] = 0xE59FF000;
      rawptr[1] = (intptr_t)replacement;
      rawptr[2] = (intptr_t)replacement;
```

I do see __aarch64__, however, running the code on an iOS device seems to crash at 

``` C++
rawptr[0] = 0xE59FF000;
```

**Comment by dascandy** [comment]
The &1 is checking whether it's a Thumb or an Arm function. In case of a Thumb function it replaces it with a thumb encoded jump opcode, with a post-fixed replacement. In case of an ARM function it replaces it with an Arm-encoded jump opcode, with again the replacement after it.

**Comment by chinux23** [comment]
Thanks for the explanation. Did you have any success on iOS devices?
I tried but it seems i was not able to unprotect the memory, thus crashing when modifying the function. But the same code works on MacOS.

**Comment by chinux23** [comment]
It seems iOS has Data Execution Prevention. It omens't allow change read+exe memory to be writable.

**Comment by dascandy** [comment]
> It seems iOS has Data Execution Prevention. It doesn't allow change read+exe memory to be writable.

That's a death knell then. If you cannot modify a function, you cannot mock it with this approach. This is a conscious OS choice though; the OS executable loader always has to be able to write to some memory and then make it executable.

I tried mostly on Raspberry Pi devices, due to on one hand their price, on the second hand their general availability and on the third hand the openness. This approach works there very well. I've also tested it on OSX, where it also works.
